---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - include_vars: "vars.yml"

    - name: Drop database
      shell: "docker exec {{ dockerContainerName }} /usr/bin/mysql -h db -u root -p{{ dbRootPassword }} -e 'drop database if exists apirc;'"

    - name: Create db if not exists
      shell: "docker exec {{ dockerContainerName }} /usr/bin/mysql -h db -u root -p{{ dbRootPassword }} -e 'create database apirc;'"
      ignore_errors: true

    - name: add user
      shell: "docker exec {{ dockerContainerName }} /usr/bin/mysql -h db -P 3306 -u root -p{{ dbRootPassword }} -e \"CREATE USER 'apirc'@'%' IDENTIFIED BY 'apirc';\""
      ignore_errors: true

    - name: privileges apirc user
      shell: "docker exec {{ dockerContainerName }} /usr/bin/mysql -h db -P 3306 -u root -p{{ dbRootPassword }} -e \"GRANT ALL PRIVILEGES ON *.* TO 'apirc'@'%';\""
