---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - include_vars: "vars.yml"

    - name: migrate
      shell: "docker exec {{ dockerContainerName }} /usr/bin/php5.6 -f /var/www/api-rc/app/artisan -- db:seed"
